--- # playbook to create and update the ssm param store
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Load variables for the particular environment
      include_vars: "{{ item }}"
      no_log: true
      with_items:
        - "../vars/main.yml"
  tasks:
    - name: test simple command
      command: uname -a

    - name: Always update a parameter store value and create a new version
      aws_ssm_parameter_store:
        name: "{{item.value.Name}}"
        description: "{{item.value.Description}}"
        string_type: "{{item.value.Type}}"
        value: "{{item.value.Value}}"
        overwrite_value: "always"
      no_log: true
      with_dict: "{{python_envs}}"